### ISSUE TITLE
Electron based platform?

### ISSUE THREAD

**Issue by joshuabuildsthings** [freetzing/freetzing#3]
Please forgive me if this has been discussed; former user of Fritzing jumping back in & trying to get caught up.

Based on the concerns about fragmenting the community & user adoption noted in #https://github.com/fritzing/fritzing-app/issues/3435 have we considered an [Electron](https://electronjs.org/) based version?

This would provide a familiar installer experience for the community while still allowing for a transition to a JS based eco-system that could concurrently support a client/server architecture.

**Comment by karpawich** [comment]
Yes, the plan is to use Electron to build the parts editor so that we can utilize the many services like Travis CI and GitHub Pages to distribute software without having to pay for any kind of website hosting. Thanks for your concern.. it is valid.
